### ISSUE TITLE
Problem when upgrading

### ISSUE THREAD

**Issue by gpapin** [chimpchimp/docker-manage-this-node#2]
Hello, I recently upgraded my docker image to the latest version and now the application won't start anymore.
Here Is the trace I have : 
```
manager        | npm info it worked if it ends with ok
manager        | npm info using npm@2.14.12
manager        | npm info using node@v4.2.6
manager        | npm info prestart manage-this-node@0.1.1
manager        | npm info start manage-this-node@0.1.1
manager        |
manager        | > manage-this-node@0.1.1 start /opt/manage-this
manager        | > node ./bin/www
manager        |
manager        | running migration
manager        | Version: 0.5
manager        | file: /opt/manage-this/lib/../config.json.0.5.1486382040491.bak
manager        | Migrated to version: 1
manager        | Version: 1
manager        | file: /opt/manage-this/lib/../config.json.1.1486382040493.bak
manager        | Migrated to version: 2
manager        | file: /opt/manage-this/lib/../config.json
manager        | /opt/manage-this/node_modules/express/node_modules/path-to-regexp/index.js:63
manager        |   path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))
manager        |                                                ^
manager        |
manager        | TypeError: Cannot read property 'length' of undefined
manager        |     at pathtoRegexp (/opt/manage-this/node_modules/express/node_modules/path-to-regexp/index.js:63:48)
manager        |     at new Layer (/opt/manage-this/node_modules/express/lib/router/layer.js:45:17)
manager        |     at Function.use (/opt/manage-this/node_modules/express/lib/router/index.js:464:17)
manager        |     at EventEmitter.<anonymous> (/opt/manage-this/node_modules/express/lib/application.js:219:21)
manager        |     at Array.forEach (native)
manager        |     at EventEmitter.use (/opt/manage-this/node_modules/express/lib/application.js:216:7)
manager        |     at Object.<anonymous> (/opt/manage-this/app.js:29:5)
manager        |     at Module._compile (module.js:410:26)
manager        |     at Object.Module._extensions..js (module.js:417:10)
manager        |     at Module.load (module.js:344:32)
manager        |
manager        | npm info manage-this-node@0.1.1 Failed to exec start script
manager        | npm ERR! Linux 4.4.0-62-generic
manager        | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
manager        | npm ERR! node v4.2.6
manager        | npm ERR! npm  v2.14.12
manager        | npm ERR! code ELIFECYCLE
manager        | npm ERR! manage-this-node@0.1.1 start: `node ./bin/www`
manager        | npm ERR! Exit status 1
manager        | npm ERR!
manager        | npm ERR! Failed at the manage-this-node@0.1.1 start script 'node ./bin/www'.
manager        | npm ERR! This is most likely a problem with the manage-this-node package,
manager        | npm ERR! not with npm itself.
manager        | npm ERR! Tell the author that this fails on your system:
manager        | npm ERR!     node ./bin/www
manager        | npm ERR! You can get their info via:
manager        | npm ERR!     npm owner ls manage-this-node
manager        | npm ERR! There is likely additional logging output above.
manager        |
manager        | npm ERR! Please include the following file with any support request:
manager        | npm ERR!     /opt/manage-this/npm-debug.log
manager        | npm info it worked if it ends with ok
manager        | npm info using npm@2.14.12
manager        | npm info using node@v4.2.6
manager        | npm info prestart manage-this-node@0.1.1
manager        | npm info start manage-this-node@0.1.1
manager        |
manager        | > manage-this-node@0.1.1 start /opt/manage-this
manager        | > node ./bin/www
```

**Comment by gpapin** [comment]
Something odd is going on during the update obviously.
I removed the existing config, started the application and then copied it back in again overriding the generated one.
It seems to work so far but an odd way to upgrade...

**Comment by chimpchimp** [comment]
There does seem to be something weird in the upgrade process but I'm not sure where it's going wrong exactly. Might be because the config file is so old or perhaps it doesn't like the fact that its a symlink, even though that's never been an issue before. I'll see if I can get it to work a little bit more cleanly.
